import { StyleSheet } from 'react-native';
import { Colors, EnhancedMealPalette as PREMIUM } from '../src/constants';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: PREMIUM.black,
    },
    safeArea: {
        flex: 1,
    },
    scrollView: {
        flex: 1,
    },
    content: {
        paddingHorizontal: 20,
        paddingBottom: 100,
    },

    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 16,
        marginBottom: 24,
    },
    backButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: PREMIUM.gray900,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
    },
    headerCenter: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: PREMIUM.white,
        letterSpacing: -0.3,
    },
    headerBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: PREMIUM.gray900,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    headerBadgeText: {
        fontSize: 10,
        fontWeight: '700',
        color: PREMIUM.accent,
        letterSpacing: 0.5,
    },
    headerRight: {
        width: 44,
    },
    settingsButton: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: PREMIUM.gray900,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
    },

    sectionTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: PREMIUM.gray400,
        textTransform: 'uppercase',
        letterSpacing: 1.2,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    dateButton: {
        backgroundColor: PREMIUM.gray900,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
    },
    dateButtonText: {
        fontSize: 12,
        fontWeight: '500',
        color: PREMIUM.gray400,
    },

    timeGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 12,
        marginBottom: 28,
    },
    timeCard: {
        backgroundColor: PREMIUM.gray900,
        paddingVertical: 16,
        paddingHorizontal: 12,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
        alignItems: 'center',
        position: 'relative',
        minHeight: 100,
        justifyContent: 'center',
    },
    timeCardSelected: {
        backgroundColor: PREMIUM.white,
        borderColor: PREMIUM.white,
    },
    timeCardEmoji: {
        fontSize: 32,
        marginBottom: 8,
    },
    timeCardLabel: {
        fontSize: 14,
        fontWeight: '700',
        color: PREMIUM.white,
        marginBottom: 2,
    },
    timeCardLabelSelected: {
        color: PREMIUM.black,
    },
    timeCardTime: {
        fontSize: 11,
        color: PREMIUM.gray600,
    },
    timeCardTimeSelected: {
        color: PREMIUM.gray600,
    },
    timeCardCheck: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: PREMIUM.accent,
        justifyContent: 'center',
        alignItems: 'center',
    },

    imageContainer: {
        position: 'relative',
        borderRadius: 20,
        overflow: 'hidden',
        marginBottom: 28,
        backgroundColor: PREMIUM.gray900,
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
    },
    imagePreview: {
        width: '100%',
        height: 240,
        backgroundColor: PREMIUM.gray800,
    },
    imageOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 100,
    },
    clearImageButton: {
        position: 'absolute',
        top: 12,
        right: 12,
    },
    clearImageBlur: {
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        overflow: 'hidden',
    },
    imageReadyBadge: {
        position: 'absolute',
        bottom: 16,
        left: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: Colors.overlayBlack70,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 12,
    },
    imageReadyText: {
        fontSize: 12,
        fontWeight: '600',
        color: PREMIUM.white,
    },
    imagePickerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: PREMIUM.gray900,
        borderRadius: 20,
        padding: 24,
        marginBottom: 28,
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
        borderStyle: 'dashed',
    },
    imagePickerButton: {
        flex: 1,
        alignItems: 'center',
        gap: 8,
    },
    imagePickerIconContainer: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: PREMIUM.gray800,
        justifyContent: 'center',
        alignItems: 'center',
    },
    imagePickerLabel: {
        fontSize: 13,
        fontWeight: '500',
        color: PREMIUM.gray200,
    },
    imageDivider: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
    },
    imageDividerLine: {
        width: 1,
        height: 40,
        backgroundColor: PREMIUM.gray800,
    },
    imageDividerText: {
        fontSize: 12,
        color: PREMIUM.gray600,
        paddingHorizontal: 8,
    },

    detailsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    detailsOptional: {
        backgroundColor: PREMIUM.gray900,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
    },
    detailsOptionalText: {
        fontSize: 10,
        fontWeight: '500',
        color: PREMIUM.gray600,
    },
    detailsContainer: {
        backgroundColor: PREMIUM.gray900,
        borderRadius: 16,
        padding: 16,
        marginBottom: 28,
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
    },
    detailsIconRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 12,
    },
    detailsHint: {
        fontSize: 12,
        color: PREMIUM.gray400,
    },
    detailsInput: {
        fontSize: 14,
        color: PREMIUM.white,
        minHeight: 50,
        textAlignVertical: 'top',
    },
    detailsTags: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: PREMIUM.gray800,
    },
    detailsTag: {
        backgroundColor: PREMIUM.gray800,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
    },
    detailsTagText: {
        fontSize: 12,
        color: PREMIUM.gray200,
    },

    analyzeButton: {
        backgroundColor: PREMIUM.accent,
        borderRadius: 16,
        paddingVertical: 18,
        paddingHorizontal: 20,
        marginBottom: 8,
    },
    analyzeButtonLoading: {
        opacity: 0.8,
    },
    analyzeButtonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    analyzeButtonIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: Colors.overlayBlack10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    analyzeButtonEmoji: {
        fontSize: 24,
    },
    analyzeButtonTexts: {
        flex: 1,
    },
    analyzeButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: PREMIUM.black,
    },
    analyzeButtonSubtext: {
        fontSize: 12,
        color: Colors.overlayBlack60,
        marginTop: 1,
    },
    betaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        marginBottom: 28,
    },
    betaText: {
        fontSize: 11,
        color: PREMIUM.gray600,
    },

    scoreCard: {
        marginBottom: 20,
    },
    scoreCardInner: {
        backgroundColor: PREMIUM.gray900,
        borderRadius: 24,
        padding: 24,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
    },
    scoreHeader: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    scoreTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        flex: 1,
    },
    scoreTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: PREMIUM.white,
        flex: 1,
    },
    scoreBadge: {
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 10,
    },
    scoreBadgeText: {
        fontSize: 12,
        fontWeight: '700',
    },
    scoreCircleContainer: {
        alignItems: 'center',
        marginBottom: 20,
    },
    scoreCircle: {
        width: 120,
        height: 120,
        borderRadius: 60,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    scoreValue: {
        fontSize: 48,
        fontWeight: '800',
        color: PREMIUM.white,
    },
    scoreMax: {
        fontSize: 16,
        fontWeight: '600',
        color: PREMIUM.gray400,
    },
    scoreDescription: {
        fontSize: 14,
        color: PREMIUM.gray200,
        textAlign: 'center',
        lineHeight: 22,
    },

    suggestionsCard: {
        backgroundColor: PREMIUM.gray900,
        borderRadius: 20,
        padding: 20,
        marginBottom: 28,
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
    },
    suggestionsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 16,
    },
    suggestionsIconWrap: {
        width: 32,
        height: 32,
        borderRadius: 10,
        backgroundColor: Colors.overlayWarning15,
        justifyContent: 'center',
        alignItems: 'center',
    },
    suggestionsTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: PREMIUM.white,
    },
    suggestionItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 10,
        marginBottom: 12,
    },
    suggestionBullet: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: PREMIUM.gray800,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 2,
    },
    suggestionText: {
        flex: 1,
        fontSize: 14,
        color: PREMIUM.gray200,
        lineHeight: 22,
    },

    descriptionContainer: {
        backgroundColor: PREMIUM.gray900,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: PREMIUM.gray800,
        marginBottom: 28,
        overflow: 'hidden',
    },
    descriptionInput: {
        padding: 16,
        fontSize: 14,
        color: PREMIUM.white,
        minHeight: 100,
    },

    saveButton: {
        backgroundColor: PREMIUM.teal,
        borderRadius: 16,
        paddingVertical: 18,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 10,
    },
    saveButtonDisabled: {
        opacity: 0.6,
    },
    saveButtonText: {
        fontSize: 16,
        fontWeight: '700',
        color: PREMIUM.white,
    },
});
